schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0"
    hash = "sha256-APnPAcmItvtJ5Zsy863lzR2TjEBF9Y66TY1e4M1ap98="
  [mod."github.com/AndreasBriese/bbloom"]
    version = "v0.0.0-20190825152654-46b345b51c96"
    hash = "sha256-ydIJ4QKvQsDSAook9y0doDaTeXpyQUy1T+ySfOgFLAg="
  [mod."github.com/BurntSushi/toml"]
    version = "v1.2.1"
    hash = "sha256-Z1dlsUTjF8SJZCknYKt7ufJz8NPGg9P9+W17DQn+LO0="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.0"
    hash = "sha256-JaGYNQwDxFCsLwzYVoJY4RUpP4dtiRlV14t2dVAg4oQ="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.2.3"
    hash = "sha256-1GLZic3WQIBZGyjvyHbfcZ/7EV7oNzNhkwEiiTpVfL4="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.0"
    hash = "sha256-TQ0AvXZfuT3PDnb4p/h5zmyT8m9VPcwxlXMJuVD6ltE="
  [mod."github.com/alecthomas/chroma/v2"]
    version = "v2.5.0"
    hash = "sha256-eYjXjerKbWc3IZACr771c3y3kFQmhmeahU57N8Nfbtw="
  [mod."github.com/antlr/antlr4/runtime/Go/antlr"]
    version = "v1.4.10"
    hash = "sha256-QZn1eltqxkZYvf7g/GQv6HftH+OuKJTVjIjyyHZw9jI="
  [mod."github.com/aryann/difflib"]
    version = "v0.0.0-20210328193216-ff5ff6dc229b"
    hash = "sha256-QaGcdek1bA6eekbxVTDaidFZrWeGk+of35NTV94lVXw="
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20210307081110-f21760c49a8d"
    hash = "sha256-5ZVRCOiNcvpmK3/mhtF1Iy0naPFVVhmXXQmC6eaJExk="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/caddy-dns/namecheap"]
    version = "v0.0.0-20211109044219-3e5991606a7a"
    hash = "sha256-MtKcYiU0m0I1O8cncwF8GbhueuQwEPhbsTabe+BBZJA="
  [mod."github.com/caddy-dns/netlify"]
    version = "v1.0.1"
    hash = "sha256-VVDza1ChdBTmZLdGLlKuEfk3kEEAefK0A6fcDDNi2AI="
  [mod."github.com/caddyserver/caddy/v2"]
    version = "v2.6.3"
    hash = "sha256-he7tWqaa+65Ujk3xxNC9XcNS/4K1kslORyZKQdtg2eg="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.17.2"
    hash = "sha256-FPvR3VeoI+VdMkrkT+TUSgpnlMm85gUqlFfq8/HMo9c="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.1.2"
    hash = "sha256-35Dk9c8Om+NSVKGwu8MwJkB8ig8mDLRviCIYbIRAgiE="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chzyer/readline"]
    version = "v0.0.0-20180603132655-2972be24d48e"
    hash = "sha256-2Uj5LGpHEbLQG3d/7z9AL8DknUBZyoTAMs4j+VVDmIA="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/dgraph-io/badger"]
    version = "v1.6.2"
    hash = "sha256-D/iXyiNZ8/7tBtA9msk10vVWfohWEPqFdobzRwKlvQQ="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.0"
    hash = "sha256-01jneg1+1x8tTfUTBZ+6mHkQaqXVnPYxLJyJhJQcvt4="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.7.0"
    hash = "sha256-Z/M62esiZ0fVwvueVQhwz18z0eS22LZ3DJ4O8FKp3AY="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.3"
    hash = "sha256-qV3UPYKKBQDTzAUzzsTpfdbGhFnkmTO/r5ylPL1SyfA="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.4.0"
    hash = "sha256-LwOrfDN5fx/R2lgaD90RIu2NxcJDpyqYEURLc9Kgxgw="
  [mod."github.com/go-chi/chi"]
    version = "v4.1.2+incompatible"
    hash = "sha256-KpvSwEqRBeUBZae9r7J3sMCpJMqyaKtEn1KKfKTa0O0="
  [mod."github.com/go-kit/kit"]
    version = "v0.10.0"
    hash = "sha256-fkr/mndYfh5dSepwRggu3ZIpwAomvwrg4LQ/foBpAd4="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.5.1"
    hash = "sha256-t50m9ffvW8PiGvO+2svnLI+N/XaWaBS+ZlhwrEQn2gU="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-openapi/analysis"]
    version = "v0.21.4"
    hash = "sha256-W+tDQJ6mwhUoKQO5AB6xHCu8n5K9DsSz7Z89Wol5zxA="
  [mod."github.com/go-openapi/errors"]
    version = "v0.20.3"
    hash = "sha256-unuZ9+J0o606DRdTFOvZFaeMY7JcsD/RG+9W3w87zlE="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.6"
    hash = "sha256-C/ICmPQu0faBiZ/qCHoy6Nzyy2FDO5QiahzlXSCwvIw="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.2"
    hash = "sha256-klWZKK7LZqSg3HMIrSkjh/NwaZTr+8kTW2ok2+JlioE="
  [mod."github.com/go-openapi/loads"]
    version = "v0.21.2"
    hash = "sha256-rAomEEL0rgthNa6XlN0tjTMUjXqkNmyFFpQmIoh4hmU="
  [mod."github.com/go-openapi/runtime"]
    version = "v0.19.24"
    hash = "sha256-bMNx+ogfhLB+F2mGAC6vlMt8uNBa6C1yGMcJjjDlgjc="
  [mod."github.com/go-openapi/spec"]
    version = "v0.20.8"
    hash = "sha256-1hj2wZBodG0yw86vEKL9+u1LGwHRXrhRVDzvGpM8o9M="
  [mod."github.com/go-openapi/strfmt"]
    version = "v0.21.3"
    hash = "sha256-tg2JEoiNcMIyRHntVIW0UMuKchfl4jYZoHchOsVRVj4="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.3"
    hash = "sha256-iUGFBMt9RobFG+Qsy2zKWEjFARi2xCSCaV2HRDL0vw4="
  [mod."github.com/go-openapi/validate"]
    version = "v0.20.0"
    hash = "sha256-5ydNvS0284/ZVFsipaOmnRgliphiOmV2ROWJPDp+t50="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.6.0"
    hash = "sha256-mMIiUN5XUXxYOpdlMQMFzYB4AX2xrpGgkkEBL0jLKrg="
  [mod."github.com/go-task/slim-sprig"]
    version = "v0.0.0-20210107165309-348f09dbbbc0"
    hash = "sha256-jgza4peLzeJlwmMh/c1gNkmtwA9YtSdGaBzBUDXhIZo="
  [mod."github.com/golang/glog"]
    version = "v1.1.0"
    hash = "sha256-FgkBzn32nsq5Fpz0KKOrOqKap6pa2A1P3N2C0/Qp820="
  [mod."github.com/golang/mock"]
    version = "v1.6.0"
    hash = "sha256-fWdnMQisRbiRzGT3ISrUHovquzLRHWvcv1JEsJFZRno="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/cel-go"]
    version = "v0.13.0"
    hash = "sha256-J1K+7oGrGrZanRzomfqhlHN681wElApLa9RCyV5lR2Y="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20210407192527-94a9f03dee38"
    hash = "sha256-ryvI75ePFCfy0qvAhEFbtB/c/Er7nvLwm7CVASBRhsI="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.16.0"
    hash = "sha256-wLymGic7wZ6fSiBYDAaGqnQ9Ste1fUWeqXeolZXCHvI="
  [mod."github.com/huandu/xstrings"]
    version = "v1.3.3"
    hash = "sha256-xtauGYk7SnC2LMnCD+dc5dBhNFNfFnkWXcKyHQNaaK0="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.12"
    hash = "sha256-IPGunEznxlUilS22LUU4p/QTA7f5+Goowf1Utg9ARpc="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.1"
    hash = "sha256-ZTP9pLgwAAvHYK5A4PqwWCHGt00x5zMSOpCPoomQ3Sg="
  [mod."github.com/jackc/chunkreader/v2"]
    version = "v2.0.1"
    hash = "sha256-LNAEmbsxWOVPtcQ1fE1JC1yTaqyvZGa/k4zocWFBRTo="
  [mod."github.com/jackc/pgconn"]
    version = "v1.13.0"
    hash = "sha256-1QNjsoscaePUciE7oWFvQs4888mKBmsb65qOx1kB3/M="
  [mod."github.com/jackc/pgio"]
    version = "v1.0.0"
    hash = "sha256-4W0PGZlkbBZcSJmPyXi9v1gAJIK9ujVLlcbxEOx9J1A="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgproto3/v2"]
    version = "v2.3.1"
    hash = "sha256-yd881PXdx7IgH1Wkh5cpP2nxEmvJcseaCPyHN9f/njo="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20200714003250-2b9c44734f2b"
    hash = "sha256-sNfMMlmdlb5P4a4EgIHaHOcHD9N6IflYHjWj0hSI640="
  [mod."github.com/jackc/pgtype"]
    version = "v1.12.0"
    hash = "sha256-ga0fZLXBxbBbs38GBRZe8QItCMi/9Fjqe1a/MBbQNE8="
  [mod."github.com/jackc/pgx/v4"]
    version = "v4.17.2"
    hash = "sha256-KNzoeOagxstBLoPhNPoNCOA/wjY7vKfiYm6vyMRpaKk="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.15"
    hash = "sha256-fMVJFz/P37vjZAf82nHjaItaB3gesOa+xV7uBuo3kmg="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.3"
    hash = "sha256-NVZKsh72dMgJetJsbLpctSGRaiCW0mC1WMKydOJgFpw="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.1"
    hash = "sha256-bxEY0wYu4Um0t7sakLyMwMPDXfv2x07gjckKSyAypsc="
  [mod."github.com/libdns/namecheap"]
    version = "v0.0.0-20211109042440-fc7440785c8e"
    hash = "sha256-fwfCHhHsLDnktt5nqaGUJi/TwZ/sOmzXd9DmPnX2M+8="
  [mod."github.com/libdns/netlify"]
    version = "v1.0.2"
    hash = "sha256-6ZCmiv/jbkSS3uB6B/6W1YX+YOYuZ86t+bZ7bz1E9hY="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.8"
    hash = "sha256-TBXc2n5tRebabjt0HipS8wCdRml0kM0JjpppUbdx1XQ="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.13"
    hash = "sha256-8dof20YZW6ado90UG9kDrjCAnlWyRSOE3Jw4K3WEZyQ="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/mholt/acmez"]
    version = "v1.0.4"
    hash = "sha256-HXGdY4WtS5V70hWRScTzQdc/3OY5gp5aRzCfIfWIqVo="
  [mod."github.com/mholt/caddy-dynamicdns"]
    version = "v0.0.0-20231219030520-b7b54f0510fc"
    hash = "sha256-q5pwjoS1EMP/D+mzf/L1dPw1Iv4ge75L2dWd14ynrmg="
  [mod."github.com/micromdm/scep/v2"]
    version = "v2.1.0"
    hash = "sha256-vs0CBvUVXRh6n+XI7GlvdijNC9/Vec0LpywCCEivo0g="
  [mod."github.com/miekg/dns"]
    version = "v1.1.50"
    hash = "sha256-mtf3QAk46pCA0a1K+oH6a7oqsY6LR6Qr8HD4qnDqe+s="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/netlify/open-api/v2"]
    version = "v2.12.2"
    hash = "sha256-BXXtZt5ZseEilCaXPiL0SpOyJ8YZeTV5Meu/43wfCsY="
  [mod."github.com/oklog/ulid"]
    version = "v1.3.1"
    hash = "sha256-LNn883rYNiaoY9sGEPIzlMRx5UwGThdYTjXqfzeGc9k="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.2.0"
    hash = "sha256-+VzAN6pB5DwEqT/KHdhgfPnWBtyIIcHi1J4HQkqCvvU="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.14.0"
    hash = "sha256-dpgGV8C30ZCn7b9mQ+Ye2AfPXTIuHLQbl2olMKzJKxA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.3.0"
    hash = "sha256-vP+miJfsoK5UG9eug8z/bhAMj3bwg66T2vIh8WHoOKU="
  [mod."github.com/prometheus/common"]
    version = "v0.37.0"
    hash = "sha256-B2v0WsP8uKWYBpZcrog/sQXStIXwWZcVLmfPgnh1ZZA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.8.0"
    hash = "sha256-hgrilokQsXCOCCvwgOSfuErxoFAQpXM/+zNJKcMVHyM="
  [mod."github.com/quic-go/qpack"]
    version = "v0.4.0"
    hash = "sha256-QWIumzmHD94DlNp9G3AQf9QCtF+Kv0pShT1+FH7/I/c="
  [mod."github.com/quic-go/qtls-go1-18"]
    version = "v0.2.0"
    hash = "sha256-NsyHh4Mk3w3XWis19stBNhtZifACiK+NpYHzh6kNHy4="
  [mod."github.com/quic-go/qtls-go1-19"]
    version = "v0.2.0"
    hash = "sha256-3sLc5OD+goNaifis2pb26NxUE5kgzorXD6kS0Dh1V30="
  [mod."github.com/quic-go/qtls-go1-20"]
    version = "v0.1.0"
    hash = "sha256-ejYlpHoylEzboH4b7uxTsaz5KKrIc4NB7SYjn4bDsIk="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.32.0"
    hash = "sha256-iZtwvZx3EvBziYQRX1BIQI48yMAQ9e+EeSVOO1+Gsgg="
  [mod."github.com/rs/xid"]
    version = "v1.4.0"
    hash = "sha256-X7WH1cxWBof4m8ZWCnP0VYQdwzBti2eoa/sqm3BmLcg="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shopspring/decimal"]
    version = "v1.2.0"
    hash = "sha256-f4Sk7p3S4ClpJN9sfm5MOJhWftcXrGgpX2ArRLt8TBg="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/slackhq/nebula"]
    version = "v1.6.1"
    hash = "sha256-wN7zB/iB1mjfG5KyS3yvxaYu12VgkNzV7z9i2Yaod7Q="
  [mod."github.com/smallstep/certificates"]
    version = "v0.23.2"
    hash = "sha256-TsNxhq85cIeOQg132SOggFjd9+2ZnSdb2jDmbu4g9B4="
  [mod."github.com/smallstep/nosql"]
    version = "v0.5.0"
    hash = "sha256-NK1vuxk+C0lnXzMIaolCn8SnGTghjgY/IXPHL3Hah9w="
  [mod."github.com/smallstep/truststore"]
    version = "v0.12.1"
    hash = "sha256-Kboc+343ZeGFeCnYxeH2Wd04M2Gsk9CNMAMnA0keRxk="
  [mod."github.com/spf13/cast"]
    version = "v1.4.1"
    hash = "sha256-jaY+/RKUviKnE2h8Ly5cdZYinSE0uc32FW6+xfZ1Ghs="
  [mod."github.com/spf13/cobra"]
    version = "v1.6.1"
    hash = "sha256-80B5HcYdFisz6QLYkTyka7f9Dr6AfcVyPwp3QChoXwU="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.2.0"
    hash = "sha256-Vc8Ecx5DBeAK89TgqxaHV7TUrpjGMUdV6cOc3FM297A="
  [mod."github.com/tailscale/tscert"]
    version = "v0.0.0-20230124224810-c6dc1f4049b2"
    hash = "sha256-0wDs4lHMgM+NTf82yBx7uNZYiyOsB5FrjbFGLjg4Ygo="
  [mod."github.com/urfave/cli"]
    version = "v1.22.12"
    hash = "sha256-FTdBlhQvyDhgrDcSJDxgSLS/cBSP8B1BC/AxGA9Lyss="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.4"
    hash = "sha256-4he5sGi0uj1LogdqvgpvN8b7p6qlKMGuWXRFzh+FK8s="
  [mod."github.com/yuin/goldmark-highlighting/v2"]
    version = "v2.0.0-20220924101305-151362477c87"
    hash = "sha256-3ADuEiUgqK7LiaakT9DfKh795GNfFKBq/dIu5Tez01o="
  [mod."gitlab.com/NebulousLabs/fastrand"]
    version = "v0.0.0-20181126182046-603482d69e40"
    hash = "sha256-ANkqamSQYAoDO03ua//PRdleh6l3m9pJeyH8rRuLuPo="
  [mod."gitlab.com/NebulousLabs/go-upnp"]
    version = "v0.0.0-20211002182029-11da932010b6"
    hash = "sha256-waDV9T6LJqSiTdV50Omm1bk/Dhcd0hwCmFHxYgY1tqs="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.6"
    hash = "sha256-DenVAmyN22xUiivk6fdJp4C9ZnUJXCMDUf8E0goRRV4="
  [mod."go.mongodb.org/mongo-driver"]
    version = "v1.11.1"
    hash = "sha256-9MxPT9X9bH1NP+KKqGr3yfqCV7ud3rRqNMHHyL5E4Qg="
  [mod."go.mozilla.org/pkcs7"]
    version = "v0.0.0-20210826202110-33d05740a352"
    hash = "sha256-x5OuHrnMWNfcLZCyQ6zaGm+ah8DMli2CCQg5z6qWgb8="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.44.0"
    hash = "sha256-V1fEoq1PpHB7KJ6ScfRNGFIrmMV03gOlyXCSCDQkLws="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.18.0"
    hash = "sha256-gRETIwDXVMuxGZEoX2/SXkMvxNI3j7Qz0FCAYh2bKZ0="
  [mod."go.opentelemetry.io/otel/exporters/otlp/internal/retry"]
    version = "v1.4.0"
    hash = "sha256-w2Mijx+TrOtmvXRXhqD11HUy4UAQjFczA5DbTtnIjRI="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.4.0"
    hash = "sha256-5Dgje2N72xfXuVq37mTxYHBoqJ6hElQtWMhcdgOMLfA="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.4.0"
    hash = "sha256-foDkdUPzhDbII2tusO2hzN7eKoaoz6oam+4d/CUh8/Q="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.18.0"
    hash = "sha256-rSQRem8ZO6N7LKgRikJ3Ffv6g1dMeXUh+cOwT/VLuPM="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.13.0"
    hash = "sha256-4gzdquW3wLlNN9HuN6X2ZRxDUuq1O8xViYB+rfEOqFk="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.18.0"
    hash = "sha256-wLwQZwb7dw6lbhBm2i1Pm8SpVW+XDmOKYYm/HE/b/w4="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v0.12.0"
    hash = "sha256-2faHqCARouQft8l8xuHmJW+NWuB8vz9Pl8HR9J7q4WI="
  [mod."go.step.sm/cli-utils"]
    version = "v0.7.5"
    hash = "sha256-ghW15CjqPsMYm03E8iqVVv6+lRjJumWoSRhxxf6VCzE="
  [mod."go.step.sm/crypto"]
    version = "v0.23.2"
    hash = "sha256-DzBVOv9BP4ZKamNDhH1GkrfH8p266McjopNO+107dhM="
  [mod."go.step.sm/linkedca"]
    version = "v0.19.0"
    hash = "sha256-2P+JMeECHxoBzFL6LUnSg6IhtuMDDSp5qTpu9TL9uKI="
  [mod."go.uber.org/atomic"]
    version = "v1.9.0"
    hash = "sha256-D8OtLaViqPShz1w8ijhIHmjw9xVaRu0qD2hXKj63r4Q="
  [mod."go.uber.org/multierr"]
    version = "v1.8.0"
    hash = "sha256-WHWgw6hLI4tPKEqJt+WC38yt64OGCXfkUJDem6mM+Mw="
  [mod."go.uber.org/zap"]
    version = "v1.24.0"
    hash = "sha256-yLzjFbMWnc5b033gcPLGP0KY1xWPJ3sjnUG/RndmC3o="
  [mod."golang.org/x/crypto"]
    version = "v0.17.0"
    hash = "sha256-/vzBaeD/Ymyc7cpjBvSfJfuZ57zWa9LOaZM7b33eIx0="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20221205204356-47842c84f3db"
    hash = "sha256-HWHDTTbsKZp1bMN06ZKluiLt8Yfjtnf1XhR9GWp4rQk="
  [mod."golang.org/x/mod"]
    version = "v0.8.0"
    hash = "sha256-cgtmxQA937+MdXUiPrVeDvRoqhxD4hvIbtXAjK2SM8U="
  [mod."golang.org/x/net"]
    version = "v0.17.0"
    hash = "sha256-qRawHWLSsJ06QNbLhUWPXGVSO1eaioeC9xZlUEWN8J8="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.15.0"
    hash = "sha256-n7TlABF6179RzGq3gctPDKDPRtDfnwPdjNCMm8ps2KY="
  [mod."golang.org/x/term"]
    version = "v0.15.0"
    hash = "sha256-rsvtsE7sKmBwtR+mhJ8iUq93ZT8fV2LU+Pd69sh2es8="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/tools"]
    version = "v0.6.0"
    hash = "sha256-J0q+C3WDTK9yyHX90FV6qr6n9H07YglYg1p4H3MqyH4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20230410155749-daa745c078e1"
    hash = "sha256-zHQgvWQBBK32YAIS2xLdO4Cg0xm6+z3IOZ2HstXPr4Y="
  [mod."google.golang.org/grpc"]
    version = "v1.56.3"
    hash = "sha256-5/b/IY6uJ6OF1JJHl1RzuMXt1rOjZ+ls9mYQyh2kTl8="
  [mod."google.golang.org/protobuf"]
    version = "v1.30.0"
    hash = "sha256-Y07NKhSuJQ2w7F7MAINQyBf+/hdMHOrxwA3B4ljQQKs="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/square/go-jose.v2"]
    version = "v2.6.0"
    hash = "sha256-GRzbqF2tkyZ8/XEDkGNxF7TxBxd3z3umy/zD6jqGNqw="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."howett.net/plist"]
    version = "v1.0.0"
    hash = "sha256-sySpZjk+EXYSv4cqtRiyVWOQ68W/SlrE/uyI4o/5CGY="
